server:
  port: 8081

spring:
#  data:
#    mongodb:
#      uri: mongodb://admin:1234@localhost:27017/aichatdb?authSource=admin
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen2.5:3b-instruct-q4_K_M
#          temperature: 0.2
#      embedding:
#        options:
#          model: nomic-embed-text
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.2


#    chat:
#      memory:
#        repository:
#          mongodb:
#            initialize-schema: true

    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        streamable-http:
          connections:
            postgres:
              url: http://localhost:8080/mcp
            export data:
              url: http://localhost:8091/mcp


logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    io.modelcontextprotocol: INFO
    org.springframework.ai.mcp: DEBUG